nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
yarnPath: .yarn/releases/yarn-3.2.1.cjs
packageExtensions:
  "@open-web3/orml-types@*":
    peerDependenciesMeta:
      "@polkadot/api":
        optional: true
  "@acala-network/types@*":
    peerDependenciesMeta:
      "@polkadot/api":
        optional: true
  "@acala-network/api@*":
    peerDependenciesMeta:
      "@polkadot/types":
        optional: true